if(APPLE)
    set(APP_PROJECT_NAME "ICQ")
    set(APP_OUTPUT_NAME "${APP_PROJECT_NAME}")
elseif(UNIX)
    set(APP_PROJECT_NAME "icq")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()
set(HAS_WEB_ENGINE OFF)