if(APPLE)
    set(APP_PROJECT_NAME "ICQ")
    set(APP_OUTPUT_NAME "${APP_PROJECT_NAME}")
    set(QT_WEBENGINE_PROCESS_NAME "QtWebEngineProcess")
    set(QT_WEBENGINE_PROCESS_TARGET_NAME "QtWebEngineProcess")
elseif(UNIX)
    set(APP_PROJECT_NAME "icq")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()
if(APPLE)
    set(HAS_WEB_ENGINE ON)
else()
    set(HAS_WEB_ENGINE OFF)
endif()
set(HAS_OAUTH2 OFF)