if(APPLE)
    set(APP_PROJECT_NAME "Mail.Ru_Agent")
elseif(UNIX)
    set(APP_PROJECT_NAME "agent")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()