if(APPLE)
    set(APP_PROJECT_NAME "Mail.Ru_Agent")
    set(APP_OUTPUT_NAME "Mail.ru Agent")
elseif(UNIX)
    set(APP_PROJECT_NAME "agent")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()
set(HAS_WEB_ENGINE OFF)