if(APPLE)
    set(APP_PROJECT_NAME "Mail.Ru_Agent")
    set(APP_OUTPUT_NAME "Mail.ru Agent")
    set(QT_WEBENGINE_PROCESS_NAME "QtWebEngineProcess_agent")
    set(QT_WEBENGINE_PROCESS_TARGET_NAME "QtWebEngineProcess")
elseif(UNIX)
    set(APP_PROJECT_NAME "agent")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()
set(HAS_WEB_ENGINE ON)
set(HAS_OAUTH2 ON)