std::make_tuple(Themes::PixmapResourceId::FileSharingVideoDownload,					"file_sharing",		"download_icon"),
std::make_tuple(Themes::PixmapResourceId::FileSharingVideoDownloadActive,           "file_sharing",		"download_icon_active"),
std::make_tuple(Themes::PixmapResourceId::FileSharingVideoDownloadHover,            "file_sharing",		"download_icon_hover"),
std::make_tuple(Themes::PixmapResourceId::FileSharingMediaCancel,					"file_sharing",		"media_cancel"),
std::make_tuple(Themes::PixmapResourceId::FileSharingMediaCancelActive,				"file_sharing",		"media_cancel_active"),
std::make_tuple(Themes::PixmapResourceId::FileSharingMediaCancelHover,				"file_sharing",		"media_cancel_hover"),
std::make_tuple(Themes::PixmapResourceId::FileSharingMediaPlay,						"file_sharing",		"media_play"),
std::make_tuple(Themes::PixmapResourceId::FileSharingMediaPlayHover,				"file_sharing",		"media_play_hover"),

std::make_tuple(Themes::PixmapResourceId::FileSharingBlankButtonIcon48,				"file_sharing",		"blank_icon_48"),

std::make_tuple(Themes::PixmapResourceId::PreviewerReload,							"previewer",		"reloadmedia"),
std::make_tuple(Themes::PixmapResourceId::PreviewerReloadHover,						"previewer",		"reloadmedia_hover"),
