#!/usr/bin/python

import os

script_path = os.path.dirname(os.path.realpath(__file__))

release_notes_source_path = os.path.join(script_path, '../gui/main_window/ReleaseNotesText.h')
release_notes_text_path = os.path.join(script_path, '../RELEASE_NOTES')

placeholder_str = '%PLACEHOLDER%'

release_notes_source_content = \
"""
#pragma once

/* AUTOGENERATED FILE */

namespace Ui
{

namespace ReleaseNotes
{
	QString releaseNotesText()
	{
		return QT_TRANSLATE_NOOP("release_notes",
			" """ + placeholder_str + """ ");
	}
}

}
"""

with open(release_notes_text_path, 'r') as text_file:
    release_notes_text = text_file.read()

release_notes_text = release_notes_text.replace('\r\n', '\\n ')
release_notes_text = release_notes_text.replace('\n', '\\n ')
release_notes_text = release_notes_text.replace('"', '\\"')
release_notes_source_content = release_notes_source_content.replace(placeholder_str, release_notes_text)

with open(release_notes_source_path, 'w') as source_file:
    source_file.write(release_notes_source_content)
