if(APPLE)
    set(APP_PROJECT_NAME "VK_Teams")
    set(APP_OUTPUT_NAME "VK Teams")
    set(QT_WEBENGINE_PROCESS_NAME "QtWebEngineProcess")
    set(QT_WEBENGINE_PROCESS_TARGET_NAME "QtWebEngineProcess")
elseif(UNIX)
    set(APP_PROJECT_NAME "vkteams")
elseif(WIN32)
    set(APP_PROJECT_NAME "icq")
else()
    message(FATAL_ERROR "unsupported platform")
endif()
set(HAS_WEB_ENGINE ON)
set(HAS_OAUTH2 ON)